plugins {
    id "application"
}

version = '1.0'

/* *************************************************************************
 * * DEPENDENCIES                                                          *
 * ************************************************************************* */

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.beust:jcommander:1.82'
    implementation 'org.json:json:20250517'

    testImplementation 'org.junit.jupiter:junit-jupiter:6.0.0'
    testImplementation 'org.awaitility:awaitility:4.3.0'
}

/* *************************************************************************
 * * CLASS TO RUN                                                          *
 * ************************************************************************* */

application {
    mainClass = 'cds.adql.validation.ADQLValidatorRunner'
}

/* *************************************************************************
 * * JAVA VERSION                                                          *
 * ************************************************************************* */

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

/* *************************************************************************
 * * SOURCES                                                               *
 * ************************************************************************* */

sourceSets.main.java.srcDirs = ["src"]
sourceSets.main.resources.srcDirs = ["resources"]
sourceSets.test.java.srcDirs = ["test"]
sourceSets.test.resources.srcDirs = ["test-resources"]

/* *************************************************************************
 * * JUNIT TESTS CONFIGURATION                                             *
 * ************************************************************************* */

tasks.named('test') {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

/* *************************************************************************
 * * JAR MANIFEST                                                          *
 * ************************************************************************* */

tasks.named('jar') {
    manifest {
        attributes('Implementation-Version': project.version,
                   'Main-Class': 'cds.adql.validation.ADQLValidatorRunner',
                   'Class-Path': configurations.runtimeClasspath.collect { it.getName() }.join(' '))
    }
}
