org.gradle.console=verbose

# Enable output caching:
#   This is useful when working different branch and going back and forth.
#   It also applies when applying a modification and then revert it.
org.gradle.caching=true
#org.gradle.caching.debug=true

# Enable configuration caching:
#   This is very useful when running a Gradle command for the first time with a
#   big project (e.g. a lot of dependencies).
org.gradle.configuration-cache=true