name: Validator test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    
    - name: Test the ADQL Validator
      uses: gradle/gradle-build-action@v2.0.1
      with:
        build-root-directory: src/adql-validator
        arguments           : test
