name: ADQL Validation

on:
  push:
    branches: [ master, adql-validator ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      VALIDATOR_SCRIPT: ${GITHUB_WORKSPACE}/src/adql-validator/build/install/adql-validator/bin/adql-validator
      QUERIES_PATH    : ${GITHUB_WORKSPACE}/src/adql/ivoa

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    
    - name: Build the ADQL Validator
      uses: gradle/gradle-build-action@v2.0.1
      with:
        build-root-directory: src/adql-validator
        arguments           : installDist
    
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki
        path      : wiki/
    
    - name : Run ADQL validation queries
      run  : mkdir -p wiki/pullrequests ; ${{env.VALIDATOR_SCRIPT}} -r -f markdown ${{env.QUERIES_PATH}} > $OUTPUT_FILE
      env:
        OUTPUT_FILE: wiki/${{ github.event.number == 0 && 'master' ||  format('pr-{0}', github.event.number) }}.md
    
    - name: Push validation report
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        # Make sure you have that / at the end. We use rsync 
        # WIKI_DIR's default is wiki/
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: gmantelet@astro.unistra.fr
        GH_NAME: ${{ github.repository_owner }}
        #EXCLUDED_FILES: "a/ b.md"
