name: ADQL Validation

on:
  push:
    branches: [ master, adql-validator ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      VALIDATOR_SCRIPT: ${GITHUB_WORKSPACE}/src/adql-validator/build/install/adql-validator/bin/adql-validator
      QUERIES_PATH    : ${GITHUB_WORKSPACE}/src/adql/ivoa

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    
    - name: Build the ADQL Validator
      uses: gradle/gradle-build-action@v2.0.1
      with:
        build-root-directory: src/adql-validator
        arguments           : installDist
    
    - name : Run ADQL validation queries
      run  : ${{env.VALIDATOR_SCRIPT}} -r -f markdown ${{env.QUERIES_PATH}}
      shell: bash
