name: ADQL Validation

on:
  push:
    branches: [ master, adql-validator ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    
    - name: Build the ADQL Validator
      uses: gradle/gradle-build-action@v2.0.1
      with:
        build-root-directory: src/adql-validator
        arguments           : installDist
    
    - name: Test the ADQL Validator
      uses: gradle/gradle-build-action@v2.0.1
      with:
        build-root-directory: src/adql-validator
        arguments           : test
    
    - name : Run ADQL validation queries
      run  : ./build/install/adql-validator/bin/adql-validator -r -f markdown ../adql/ivoa
      shell: bash
